/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Process is alive. Never touches external systems.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Ready to serve traffic: DB + Redis reachable.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rates/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current rates */
        get: operations["current_rates_rates_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rates/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historical rates for one pair */
        get: operations["history_rates_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rates/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Convert an amount between two currencies using the current rate */
        get: operations["convert_rates_convert_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active currencies */
        get: operations["currencies_currencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sources with health */
        get: operations["sources_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email a magic sign-in link */
        post: operations["request_link_auth_request_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consume a magic link and start a session */
        get: operations["verify_auth_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List your key groups */
        get: operations["list_my_groups_keys_groups_get"];
        put?: never;
        /** Create a key group */
        post: operations["create_my_group_keys_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys/groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one group */
        get: operations["get_my_group_keys_groups__group_id__get"];
        put?: never;
        post?: never;
        /** Delete a group (cascade to its keys) */
        delete: operations["delete_my_group_keys_groups__group_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys/groups/{group_id}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List keys in a group */
        get: operations["list_group_keys_keys_groups__group_id__keys_get"];
        put?: never;
        /** Mint a new key (full value shown once) */
        post: operations["create_group_key_keys_groups__group_id__keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys/keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a key */
        delete: operations["revoke_my_key_keys_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-day + per-endpoint usage for the caller */
        get: operations["get_summary_usage_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent audit-log entries */
        get: operations["get_audit_log_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEntryInfo */
        AuditEntryInfo: {
            /**
             * Action
             * @example apikey.create
             */
            action: string;
            /** Actor User Id */
            actor_user_id: string | null;
            /** Subject Type */
            subject_type: string | null;
            /** Subject Id */
            subject_id: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Ip Address */
            ip_address: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** AuditLogResponse */
        AuditLogResponse: {
            /** Entries */
            entries: components["schemas"]["AuditEntryInfo"][];
        };
        /** BaseRatesResponse */
        BaseRatesResponse: {
            /**
             * Base
             * @example USD
             */
            base: string;
            /** Rates */
            rates: components["schemas"]["RatePoint"][];
        };
        /**
         * CircuitState
         * @description Per-source breaker state. Mirrors the DB check constraint on source_health.
         * @enum {string}
         */
        CircuitState: "closed" | "open" | "half_open";
        /** ConvertResponse */
        ConvertResponse: {
            /** From */
            from: string;
            /** To */
            to: string;
            /** Amount */
            amount: string;
            /** Rate */
            rate: string;
            /** Result */
            result: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** CurrenciesResponse */
        CurrenciesResponse: {
            /** Currencies */
            currencies: components["schemas"]["CurrencyInfo"][];
        };
        /** CurrencyInfo */
        CurrencyInfo: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Symbol */
            symbol: string | null;
            /** Decimal Digits */
            decimal_digits: number;
            /** Tier */
            tier: string;
        };
        /** GroupCreateInput */
        GroupCreateInput: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** GroupInfo */
        GroupInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Keys Count */
            keys_count: number;
        };
        /** GroupsResponse */
        GroupsResponse: {
            /** Groups */
            groups: components["schemas"]["GroupInfo"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryPoint */
        HistoryPoint: {
            /** Rate */
            rate: string;
            /** Confidence */
            confidence: string | null;
            /** Sources Count */
            sources_count: number | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Base */
            base: string;
            /** Target */
            target: string;
            /** Points */
            points: components["schemas"]["HistoryPoint"][];
        };
        /** KeyCreateInput */
        KeyCreateInput: {
            /** Name */
            name: string;
            /**
             * Scopes
             * @example [
             *       "rates:read"
             *     ]
             */
            scopes?: string[] | null;
            /**
             * Rate Limit Per Min
             * @example 60
             */
            rate_limit_per_min?: number | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /**
         * KeyCreatedResponse
         * @description Full key is shown exactly once; callers should copy it immediately.
         */
        KeyCreatedResponse: {
            /**
             * Key
             * @description The full `koel_...` key — store it now, we won't show it again
             */
            key: string;
            info: components["schemas"]["KeyInfo"];
        };
        /** KeyInfo */
        KeyInfo: {
            /** Id */
            id: string;
            /** Group Id */
            group_id: string;
            /** Name */
            name: string;
            /** Key Prefix */
            key_prefix: string;
            /** Scopes */
            scopes: string[];
            /** Rate Limit Per Min */
            rate_limit_per_min: number;
            /** Is Active */
            is_active: boolean;
            /** Last Used At */
            last_used_at: string | null;
            /** Expires At */
            expires_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** KeysResponse */
        KeysResponse: {
            /** Keys */
            keys: components["schemas"]["KeyInfo"][];
        };
        /** LogoutResponse */
        LogoutResponse: {
            /** Revoked */
            revoked: number;
        };
        /**
         * RatePoint
         * @description One row of current rate data for a single target.
         */
        RatePoint: {
            /**
             * Target
             * @example EUR
             */
            target: string;
            /**
             * Rate
             * @example 0.8500
             */
            rate: string;
            /**
             * Confidence
             * @example 1.000
             */
            confidence?: string | null;
            /**
             * Sources Count
             * @example 3
             */
            sources_count: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** RequestLinkInput */
        RequestLinkInput: {
            /**
             * Email
             * Format: email
             * @example you@example.com
             */
            email: string;
        };
        /**
         * RequestLinkResponse
         * @description Returned regardless of whether the email exists — avoids enumerating users.
         */
        RequestLinkResponse: {
            /**
             * Delivered
             * @default true
             */
            delivered: boolean;
        };
        /** SinglePairResponse */
        SinglePairResponse: {
            /** Base */
            base: string;
            /** Target */
            target: string;
            /** Rate */
            rate: string;
            /** Confidence */
            confidence: string | null;
            /** Sources Count */
            sources_count: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** SourceHealthInfo */
        SourceHealthInfo: {
            circuit_state: components["schemas"]["CircuitState"];
            /** Consecutive Failures */
            consecutive_failures: number;
            /** Total Requests */
            total_requests: number;
            /** Total Failures */
            total_failures: number;
            /** Avg Latency Ms */
            avg_latency_ms: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Last Failure At */
            last_failure_at: string | null;
        };
        /** SourceInfo */
        SourceInfo: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Weight */
            weight: string;
            /** Is Active */
            is_active: boolean;
            health: components["schemas"]["SourceHealthInfo"] | null;
        };
        /** SourcesResponse */
        SourcesResponse: {
            /** Sources */
            sources: components["schemas"]["SourceInfo"][];
        };
        /** UsageDayPoint */
        UsageDayPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Requests */
            requests: number;
            /** Errors */
            errors: number;
            /** Avg Response Time Ms */
            avg_response_time_ms: string | null;
            /** Total Bytes */
            total_bytes: number;
        };
        /** UsageEndpointPoint */
        UsageEndpointPoint: {
            /** Endpoint */
            endpoint: string;
            /** Requests */
            requests: number;
            /** Errors */
            errors: number;
            /** Avg Response Time Ms */
            avg_response_time_ms: string | null;
            /** Total Bytes */
            total_bytes: number;
        };
        /** UsageSummaryResponse */
        UsageSummaryResponse: {
            /**
             * From
             * Format: date-time
             */
            from: string;
            /**
             * To
             * Format: date-time
             */
            to: string;
            /** By Day */
            by_day: components["schemas"]["UsageDayPoint"][];
            /** By Endpoint */
            by_endpoint: components["schemas"]["UsageEndpointPoint"][];
        };
        /** UserMe */
        UserMe: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @description Account role. Mirrors the DB check constraint on users.role.
         * @enum {string}
         */
        UserRole: "user" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyResponse */
        VerifyResponse: {
            user: components["schemas"]["UserMe"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    current_rates_rates_current_get: {
        parameters: {
            query: {
                /** @description ISO 4217 base code */
                base: string;
                /** @description If set, return just this pair */
                target?: string | null;
                /** @description Optional subset of targets to return (ignored when `target` set) */
                targets?: string[] | null;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseRatesResponse"] | components["schemas"]["SinglePairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_rates_history_get: {
        parameters: {
            query: {
                base: string;
                target: string;
                /** @description ISO-8601 start (inclusive) */
                since?: string | null;
                /** @description ISO-8601 end (inclusive) */
                until?: string | null;
                limit?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    convert_rates_convert_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                amount: number | string;
            };
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    currencies_currencies_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrenciesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_sources_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_link_auth_request_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestLinkInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestLinkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_auth_verify_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_groups_keys_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_my_group_keys_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupCreateInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_group_keys_groups__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_my_group_keys_groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_group_keys_keys_groups__group_id__keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeysResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_group_key_keys_groups__group_id__keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyCreateInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_my_key_keys_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_usage_summary_get: {
        parameters: {
            query?: {
                group_id?: string | null;
                key_id?: string | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_log_admin_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Filter to one action, e.g. apikey.create */
                action?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                koel_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
